version: "3"
services:
  jupyterlab:
    build: ./jupyterlab
    command:
    - start-notebook.sh
    - --NotebookApp.token='' # 認証を無効化
    - --NotebookApp.disable_check_xsrf=True # CSRFチェックを無効化
    ports:
      - "8888:8888"